// <auto-generated />
using System;
using JobMaintenanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobMaintenanceService.Migrations
{
    [DbContext(typeof(JobMaintenanceDbContext))]
    partial class JobMaintenanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JobMaintenanceService.Models.Inspection", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime(6)");
                    b.Property<Guid?>("CompletionEventId").HasColumnType("char(36)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                    b.Property<string>("IdentifiedProblems").IsRequired().HasMaxLength(2000).HasColumnType("varchar(2000)");
                    b.Property<string>("InspectionResults").IsRequired().HasMaxLength(2000).HasColumnType("varchar(2000)");
                    b.Property<bool>("IsCompleted").HasColumnType("tinyint(1)");
                    b.Property<int>("JobCardId").HasColumnType("int");
                    b.Property<string>("MechanicId").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("MechanicName").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                    b.HasKey("Id"); b.HasIndex("JobCardId").IsUnique(); b.HasIndex("MechanicId"); b.ToTable("Inspections");
                });

            modelBuilder.Entity("JobMaintenanceService.Models.JobCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CheckInId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("JobCardNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ReportedProblems")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId")
                        .IsUnique();

                    b.HasIndex("JobCardNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("JobCards");
                });

            modelBuilder.Entity("JobMaintenanceService.Models.MechanicAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MechanicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId", "IsActive");

                    b.ToTable("MechanicAssignments");
                });

            modelBuilder.Entity("JobMaintenanceService.Models.RepairNote", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                    b.Property<string>("MechanicId").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("MechanicName").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                    b.Property<int>("JobCardId").HasColumnType("int");
                    b.Property<string>("Note").IsRequired().HasMaxLength(2000).HasColumnType("varchar(2000)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                    b.HasKey("Id"); b.HasIndex("JobCardId"); b.HasIndex("MechanicId"); b.ToTable("RepairNotes");
                });

            modelBuilder.Entity("JobMaintenanceService.Models.RepairTask", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime(6)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");
                    b.Property<bool>("IsCompleted").HasColumnType("tinyint(1)");
                    b.Property<int>("JobCardId").HasColumnType("int");
                    b.Property<string>("MechanicId").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)");
                    b.Property<string>("MechanicName").IsRequired().HasMaxLength(150).HasColumnType("varchar(150)");
                    b.Property<string>("TaskDescription").IsRequired().HasMaxLength(1000).HasColumnType("varchar(1000)");
                    b.Property<string>("TaskTitle").IsRequired().HasMaxLength(200).HasColumnType("varchar(200)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime(6)");
                    b.HasKey("Id"); b.HasIndex("JobCardId"); b.HasIndex("MechanicId"); b.ToTable("RepairTasks");
                });

            modelBuilder.Entity("JobMaintenanceService.Models.JobStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChangedByRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("JobCardId")
                        .HasColumnType("int");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("JobCardId", "ChangedAt");

                    b.ToTable("JobStatusHistories");
                });

            modelBuilder.Entity("JobMaintenanceService.Models.ProcessedKafkaEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("ProcessedKafkaEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
