import { useState } from 'react'
import AccountsSidebar from '../components/AccountsSidebar'
import { partChargeApi } from '../services/api'

export default function BillingChargesPage() {
  const [jobCardId, setJobCardId] = useState('')
  const [invoice, setInvoice] = useState(null)
  const [error, setError] = useState('')
  const [form, setForm] = useState({ type: 'service', description: '', quantity: '1', unitPrice: '' })
  async function load(e) { if (e) e.preventDefault(); setError(''); try { setInvoice(await partChargeApi.getInvoice(Number(jobCardId))) } catch (err) { setError(err.message || 'Unable to load invoice.') } }
  async function addCharge(e) { e.preventDefault(); const quantity = Number(form.quantity); const unitPrice = Number(form.unitPrice); if (!form.description.trim() || quantity <= 0 || unitPrice < 0) { setError('Enter a description, a quantity greater than zero, and a non-negative unit price.'); return } try { setError(''); const data = { description: form.description.trim(), quantity, unitPrice }; const updated = form.type === 'service' ? await partChargeApi.addService(Number(jobCardId), data) : await partChargeApi.addLabour(Number(jobCardId), data); setInvoice(updated); setForm({ ...form, description: '', quantity: '1', unitPrice: '' }) } catch (err) { setError(err.message || 'Unable to add charge.') } }
  return <div className="portal-layout"><AccountsSidebar /><main className="portal-main"><header className="portal-topbar"><div><span className="portal-eyebrow">BILLING</span><h1>Invoice Charges</h1></div></header><div className="portal-content">
    <section className="portal-card"><form className="inventory-form" onSubmit={load}><label>Job card ID<input required min="1" type="number" value={jobCardId} onChange={e => setJobCardId(e.target.value)} /></label><div className="inventory-form-actions"><button className="portal-primary-button">Open invoice</button></div></form></section>
    {error && <div className="portal-error">{error}</div>}
    {invoice && <><section className="portal-card"><h2>Invoice #{invoice.id || 'New'} — Job #{invoice.jobCardId}</h2><form className="inventory-form" onSubmit={addCharge}><label>Charge type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="service">Service</option><option value="labour">Labour</option></select></label><label>Description<input required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label><label>Quantity / hours<input required type="number" min="0.0001" step="0.01" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></label><label>Unit price<input required type="number" min="0" step="0.01" value={form.unitPrice} onChange={e => setForm({ ...form, unitPrice: e.target.value })} /></label><div className="inventory-form-actions"><button className="portal-primary-button">Add {form.type} charge</button></div></form></section><section className="portal-card"><div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Type</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{invoice.chargeLines?.length ? invoice.chargeLines.map(c => <tr key={c.id}><td>{c.chargeType}</td><td>{c.description}</td><td>{c.quantity}</td><td>{Number(c.unitPrice).toFixed(2)}</td><td>{Number(c.lineTotal).toFixed(2)}</td></tr>) : <tr><td colSpan="5">No charges yet.</td></tr>}</tbody></table></div><h2>Invoice total: {Number(invoice.totalAmount || 0).toFixed(2)}</h2></section></>}
  </div></main></div>
}
