import { useEffect, useState } from 'react'
import { AlertTriangle, Boxes, ClipboardList, PackageCheck, WalletCards } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import InventorySidebar from '../components/InventorySidebar'
import { clearAuth, partRequestApi, sparePartApi } from '../services/api'

export default function InventoryDashboardPage() {
  const navigate = useNavigate(); const [stock, setStock] = useState([]); const [lowStock, setLowStock] = useState([]); const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { try { setLoading(true); setError(''); const [all, low, pending] = await Promise.all([sparePartApi.getCurrentStockReport(), sparePartApi.getLowStockReport(), partRequestApi.getPending()]); setStock(all); setLowStock(low); setRequests(pending) } catch (err) { if (err.status === 401 || err.status === 403) { clearAuth(); navigate('/login'); return }; setError(err.message || 'Unable to load inventory dashboard data.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const totalUnits = stock.reduce((sum, item) => sum + Number(item.currentQuantity || 0), 0); const value = stock.reduce((sum, item) => sum + Number(item.currentQuantity || 0) * Number(item.unitPrice || 0), 0)
  const cards = [{ label: 'Part types', value: stock.length, icon: <Boxes size={25} />, color: '#2563eb' }, { label: 'Units in stock', value: totalUnits, icon: <PackageCheck size={25} />, color: '#059669' }, { label: 'Low-stock parts', value: lowStock.length, icon: <AlertTriangle size={25} />, color: '#d97706' }, { label: 'Pending requests', value: requests.length, icon: <ClipboardList size={25} />, color: '#7c3aed' }]
  return <div className="portal-layout"><InventorySidebar /><main className="portal-main"><header className="portal-topbar"><div><span className="portal-eyebrow">INVENTORY MANAGEMENT</span><h1>Inventory Dashboard</h1></div><button className="portal-secondary-button" onClick={load}>Refresh</button></header><div className="portal-content">{error && <div className="portal-error">{error}</div>}{loading ? <div className="portal-loading-card"><div className="loading-spinner" /><p>Loading inventory dashboard...</p></div> : <><section className="portal-grid">{cards.map(card => <div className="portal-card" key={card.label} style={{ display: 'flex', gap: '16px', alignItems: 'center' }}><div style={{ color: card.color, background: `${card.color}18`, padding: '13px', borderRadius: '12px' }}>{card.icon}</div><div><span className="portal-eyebrow">{card.label}</span><h2 style={{ margin: '4px 0 0' }}>{card.value}</h2></div></div>)}</section><section className="portal-card" style={{ marginTop: '24px', display: 'flex', gap: '14px', alignItems: 'center' }}><div style={{ color: '#0f766e', background: '#ccfbf1', padding: '13px', borderRadius: '12px' }}><WalletCards size={25} /></div><div><span className="portal-eyebrow">Estimated stock value</span><h2 style={{ margin: '4px 0 0' }}>{value.toFixed(2)}</h2></div></section><section className="portal-grid" style={{ marginTop: '24px' }}><div className="portal-card"><div className="inventory-list-header"><div><h2>Low-stock attention</h2><p>Parts at or below threshold.</p></div><button className="portal-secondary-button" onClick={() => navigate('/inventory/low-stock-report')}>View report</button></div>{lowStock.length ? <div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Part</th><th>Stock</th><th>Threshold</th></tr></thead><tbody>{lowStock.slice(0, 5).map(item => <tr key={item.id}><td>{item.name}</td><td>{item.currentQuantity}</td><td>{item.lowStockThreshold}</td></tr>)}</tbody></table></div> : <p>No low-stock parts need attention.</p>}</div><div className="portal-card"><div className="inventory-list-header"><div><h2>Pending requests</h2><p>Mechanic requests ready to issue.</p></div><button className="portal-secondary-button" onClick={() => navigate('/inventory/part-requests')}>Manage requests</button></div>{requests.length ? <div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Job</th><th>Part</th><th>Requested</th></tr></thead><tbody>{requests.slice(0, 5).map(item => <tr key={item.id}><td>{item.jobCardNumber || `#${item.jobCardId}`}</td><td>{item.sparePartName}</td><td>{item.requestedQuantity}</td></tr>)}</tbody></table></div> : <p>There are no pending part requests.</p>}</div></section></>}</div></main></div>
}
