import { useEffect, useState } from 'react'
import CustomerSidebar from '../components/CustomerSidebar'
import { invoiceApi } from '../services/api'

export default function MyInvoicesPage() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { invoiceApi.getMine().then(setItems).catch(e => setError(e.message || 'Unable to load invoices.')).finally(() => setLoading(false)) }, [])
  const open = async id => { try { setError(''); setSelected(await invoiceApi.getById(id)) } catch (e) { setError(e.message || 'Unable to open invoice.') } }
  return <div className="portal-layout"><CustomerSidebar /><main className="portal-main"><header className="portal-topbar"><div><span className="portal-eyebrow">MY ACCOUNT</span><h1>My Invoices</h1></div></header><div className="portal-content">{error && <div className="portal-error">{error}</div>}<section className="portal-card"><h2>Invoices</h2>{loading ? <p>Loading invoices…</p> : items.length === 0 ? <p>You do not have any invoices yet.</p> : <div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Invoice</th><th>Vehicle</th><th>Status</th><th>Balance</th><th /></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.invoiceNumber}</td><td>{item.vehicleRegistrationNumber}</td><td>{item.paymentStatus}</td><td>{Number(item.remainingBalance).toFixed(2)}</td><td><button className="portal-primary-button" onClick={() => open(item.id)}>View</button></td></tr>)}</tbody></table></div>}</section>{selected && <section className="portal-card"><h2>Invoice {selected.invoiceNumber}</h2><p>Customer #{selected.customerId} · Vehicle: {selected.vehicleRegistrationNumber} · Job: {selected.jobCardNumber || selected.jobCardId}</p><p><strong>Payment status:</strong> {selected.paymentStatus} · Paid: {Number(selected.amountPaid).toFixed(2)} · Remaining: {Number(selected.remainingBalance).toFixed(2)}</p><div className="portal-table-wrapper"><table className="portal-table"><thead><tr><th>Type</th><th>Description</th><th>Qty</th><th>Unit price</th><th>Total</th></tr></thead><tbody>{selected.chargeLines.map(line => <tr key={line.id}><td>{line.chargeType}</td><td>{line.description}</td><td>{line.quantity}</td><td>{Number(line.unitPrice).toFixed(2)}</td><td>{Number(line.lineTotal).toFixed(2)}</td></tr>)}</tbody></table></div><h2>Total: {Number(selected.totalAmount).toFixed(2)}</h2></section>}</div></main></div>
}
